go.mod - update mito and go-internal (#8)
Update to mito v1.16.0.

Update go-internal to fix a test issue under Go 1.23. The error being
addressed is:

    /go/pkg/mod/github.com/rogpeppe/go-internal@v1.8.1/testscript/exe_go118.go:14:27:
    cannot use nopTestDeps{} (value of type nopTestDeps) as testing.testDeps
    value in argument to testing.MainStart: nopTestDeps does not implement
    testing.testDeps (missing method InitRuntimeCoverage)

[git-generate]
go get github.com/elastic/mito@v1.16.0
go get github.com/rogpeppe/go-internal@v1.13.1
go mod tidy